[build]
  command = "make netlify"
  publish = "dashboard"
  functions = "functions"
[build.environment]
  GOBIN = "/opt/build/repo/functions"
[template.environment]
  GO_IMPORT_PATH = "github.com/[your account/org]/netlify-functions-in-go"
